name: Domform
version: '1.0-SNAPSHOT'
main: com.geji.domform.Domform
api-version: '1.21'
depend: ["floodgate","Dominion"]

commands:
  domform:
    description: dom领地基岩版支持
    usage: /domform
    permission: domform.use

permissions:
  domform.use:
    description: 允许使用 Dominion form GUI
    default: true